- hosts: prd
  tasks: 
  - name: Instalando o python2, e virtualenv
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    become: yes
  - name: Git Clone
    ansible.builtin.git:
      repo: https://github.com/edsonbarreto-dev/alura_aws.git
      dest: /home/ubuntu/clients
      version: main
      force: yes
  - name: Instalando dependencias com pip (Django e Django Rest)
    pip:
      virtualenv: /home/ubuntu/clients/venv
      requirements: /home/ubuntu/clients/application/requirements.txt
  - name: Alterando o hosts do settings
    lineinfile:
      path: /home/ubuntu/clients/application/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes
  - name: Configurando o banco de dados
    shell: '. /home/ubuntu/clients/venv/bin/activate; python /home/ubuntu/clients/application/manage.py migrate'
  - name: Carregando dados iniciais
    shell: '. /home/ubuntu/clients/venv/bin/activate; python /home/ubuntu/clients/application/manage.py loaddata clientes.json'
  - name: Iniciando o servidor
    shell: '. /home/ubuntu/clients/venv/bin/activate; nohup python /home/ubuntu/clients/application/manage.py runserver 0.0.0.0:8000 &'
