- hosts: terraform-ansible-python
  tasks: 
  - name: Instalando o python2, e virtualenv
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    become: yes
  - name: Instalando dependencias com pip (Django e Django Rest)
    pip:
      virtualenv: /home/ubuntu/clients/venv
      name:
        - django
        - djangorestframework
  - name: Verificando se o projeto ja existe
    stat:
      path: /home/ubuntu/clients/setup/settings.py
    register: projeto
  - name: Iniciando o projeto
    shell: '. /home/ubuntu/clients/venv/bin/activate; django-admin startproject setup /home/ubuntu/clients/'
    when: not projeto.stat.exists
  - name: Alterando o hosts do settings
    lineinfile:
      path: /home/ubuntu/clients/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes
